[supabase_trading]
url = "https://xlwfucchgzynfzixcaed.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsd2Z1Y2NoZ3p5bmZ6aXhjYWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjkyMjksImV4cCI6MjA3Mzc0NTIyOX0.W5DJTI-AP4N6NTfVQOfDNqyrKMYDuQR9V2KNrUhlLIQ"

[supabase_valuation]
url = "https://zctxrabgbfpmeydxusij.supabase.co"
anon_key = "sb_publishable_7BgP5GHVdaDtAazJLOpahQ_QGX4WM5c"