[supabase_trading]
url = "https://xlwfucchgzynfzixcaed.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsd2Z1Y2NoZ3p5bmZ6aXhjYWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjkyMjksImV4cCI6MjA3Mzc0NTIyOX0.W5DJTI-AP4N6NTfVQOfDNqyrKMYDuQR9V2KNrUhlLIQ"

[supabase_valuation]
url = "https://zctxrabgbfpmeydxusij.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjdHhyYWJnYmZwbWV5ZHh1c2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxOTcwNTYsImV4cCI6MjA4Mzc3MzA1Nn0.ImuD-xVpXkMtpW_vN0G5UFe0JvDVqbP2dfuxc3GXu04"